[build-system]
requires = ["uv_build>=0.9.28,<0.10.0"]
build-backend = "uv_build"

[project.urls]
homepage = "https://github.com/christianwhocodes/pkg-christianwhocodes#readme"
repository = "https://github.com/christianwhocodes/pkg-christianwhocodes"
issues = "https://github.com/christianwhocodes/pkg-christianwhocodes/issues"

[project.scripts]
christianwhocodes = "christianwhocodes.cli:main"
cwc = "christianwhocodes.cli:main"

[project]
name = "christianwhocodes"
version = "1.2.7"
description = "Python utilities for developers."
readme = "README.md"
license = { file = "LICENSE" }
authors = [
    { name = "Kevin Wasike Wakhisi", email = "kevin@christianwhocodes.space" },
]
requires-python = ">=3.12"
dependencies = ["pyperclip>=1.11.0", "rich>=14.3.1"]

[[tool.uv.index]]
name = "testpypi"
url = "https://test.pypi.org/simple/"
publish-url = "https://test.pypi.org/legacy/"
explicit = true
